// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://txqilqqtrbmykqinwyea.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR4cWlscXF0cmJteWtxaW53eWVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE1NTQ1ODEsImV4cCI6MjA1NzEzMDU4MX0.ziyMe2VaNUBmULImT-HRcUa2B_OpOAnZv2u__ApwCRc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);